# Run code formatting enforcer  1.00.01 DG. 8/10/21

name: Artistic Style

# Controls when the action will run. 
# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains  1 job called "unit-test" (?)
  astyle:
    #  type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps are a sequence of tasks that will be executed
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: webfactory/ssh-agent@v0.5.3
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - uses: actions/checkout@v2

    - name: Install Astyle
      run: |
          wget -q https://sourceforge.net/projects/astyle/files/astyle/astyle%203.1/astyle_3.1_linux.tar.gz/download -O astyle.tar.gz
          tar -xvf astyle.tar.gz
          cd astyle
          mkdir as-gcc-exe
          cd as-gcc-exe
          cmake  ../
          make
          sudo make install
          cd ../../
          pwd

    - name: Run Astyle
      run: make astyle
        
    # Use diff to show required changes
    - name: Check formatting
      run: git diff --exit-code --diff-filter=d --color
